version: '3.6'

x-build-args: &build_args
  INSTALL_PYTHON_VERSION: 3.7
  INSTALL_NODE_VERSION: 12

x-default-volumes: &default_volumes
  volumes:
    - ./:/app

services:
  flask-dev:
    build:
      context: .
      target: server
      args:
        <<: *build_args
    image: "flask_fsm_test-development"
    depends_on:
      - db
    ports:
      - "5000:5000"
    <<: *default_volumes

  flask-prod:
    build:
      context: .
      target: server
      args:
        <<: *build_args
    image: "flask_fsm_test-production"
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
      LOG_LEVEL: info
      GUNICORN_WORKERS: 4
    <<: *default_volumes

  manage:
    build:
      context: .
      target: manage
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
    image: "flask_fsm_test-manage"
    stdin_open: true
    tty: true
    depends_on:
      - db
    <<: *default_volumes
  
  db:
    image: postgres:11.6-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker

volumes:
  postgres_data:
  static-build: