"""empty message

Revision ID: 9090310736f1
Revises: c53e60314da9
Create Date: 2019-11-26 09:44:47.715779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9090310736f1'
down_revision = 'c53e60314da9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.Enum('STEP_1', 'STEP_2', 'STEP_3', 'COMPLETE', name='signupstates'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    # ### end Alembic commands ###
